In [6]:
# importando os scripts de consulta

import sys
import os

# Altera o caminho para a pasta raiz do projeto (um nível acima)
raiz_projeto = os.path.abspath(os.path.join(os.getcwd(), ".."))

# Adiciona a raiz do projeto ao caminho de busca do Python se ainda não estiver lá
if raiz_projeto not in sys.path:
    sys.path.append(raiz_projeto)

    
import pandas as pd
from scripts.crm_avaliacoes import load_avaliacoes
from scripts.crm_leads import load_leads

In [17]:
avaliacoes = load_avaliacoes()

Página 1: 250 registros
Página 2: 250 registros
Página 3: 250 registros
Página 4: 250 registros
Página 5: 250 registros
Página 6: 250 registros
Página 7: 250 registros
Página 8: 250 registros
Página 9: 250 registros
Página 10: 250 registros
Página 11: 250 registros
Página 12: 250 registros
Página 13: 250 registros
Página 14: 250 registros
Página 15: 250 registros
Página 16: 250 registros
Página 17: 250 registros
Página 18: 250 registros
Página 19: 250 registros
Página 20: 250 registros
Página 21: 250 registros
Página 22: 250 registros
Página 23: 250 registros
Página 24: 250 registros
Página 25: 250 registros
Página 26: 250 registros
Página 27: 250 registros
Página 28: 250 registros
Página 29: 250 registros
Página 30: 250 registros
Página 31: 250 registros
Página 32: 250 registros
Página 33: 250 registros
Página 34: 250 registros
Página 35: 250 registros
Página 36: 250 registros
Página 37: 250 registros
Página 38: 250 registros
Página 39: 250 registros
Página 40: 250 registros
Página 41: 250 registros
Página 42: 250 registros
Página 43: 250 registros
Página 44: 250 registros
Página 45: 250 registros
Página 46: 250 registros
Página 47: 250 registros
Página 48: 250 registros
Página 49: 250 registros
Página 50: 250 registros
Página 51: 250 registros
Página 52: 250 registros
Página 53: 250 registros
Página 54: 250 registros
Página 55: 250 registros
Página 56: 250 registros
Página 57: 250 registros
Página 58: 250 registros
Página 59: 250 registros
Página 60: 250 registros
Página 61: 250 registros
Página 62: 250 registros
Página 63: 250 registros
Página 64: 250 registros
Página 65: 250 registros
Página 66: 250 registros
Página 67: 250 registros
Página 68: 250 registros
Página 69: 250 registros
Página 70: 250 registros
Página 71: 250 registros
Página 72: 250 registros
Página 73: 250 registros
Página 74: 250 registros
Página 75: 250 registros
Página 76: 250 registros
Página 77: 250 registros
Página 78: 250 registros
Página 79: 250 registros
Página 80: 250 registros
Página 81: 250 registros
Página 82: 250 registros
Página 83: 250 registros
Página 84: 250 registros
Página 85: 250 registros
Página 86: 250 registros
Página 87: 250 registros
Página 88: 250 registros
Página 89: 250 registros
Página 90: 250 registros
Página 91: 250 registros
Página 92: 250 registros
Página 93: 250 registros
Página 94: 250 registros
Página 95: 187 registros

In [18]:
avaliacoes.head(2)

,cad_avaliacaoid,createdon,cad_fatoravaliacaoid,cad_inscricaocandidatoid,cad_situacaoavaliacao,cad_valor
0,{72A71B1E-6156-F111-A825-000D3A8928F0},NaT,FATOR PRV ONL NOTA FINAL,CAN-001483-TRI,Não Avaliado,0
1,{75A71B1E-6156-F111-A825-000D3A8928F0},NaT,FATOR PRV OBJ ONL(INFORMADO),CAN-001483-TRI,Não Avaliado,0

In [19]:
avaliacoes['cad_valor'] = avaliacoes['cad_valor'].astype(float)
avaliacoes_agrupado = avaliacoes[[ 'cad_inscricaocandidatoid' , 'cad_valor']].groupby('cad_inscricaocandidatoid').agg({'cad_valor': 'sum'}).reset_index()

### Carregamento dos leads

In [7]:
leads = load_leads()

Página 1: 250 registros
Página 2: 250 registros
Página 3: 250 registros
Página 4: 250 registros
Página 5: 250 registros
Página 6: 250 registros
Página 7: 250 registros
Página 8: 250 registros
Página 9: 250 registros
Página 10: 250 registros
Página 11: 250 registros
Página 12: 250 registros
Página 13: 250 registros
Página 14: 250 registros
Página 15: 250 registros
Página 16: 250 registros
Página 17: 250 registros
Página 18: 250 registros
Página 19: 250 registros
Página 20: 250 registros
Página 21: 250 registros
Página 22: 250 registros
Página 23: 250 registros
Página 24: 250 registros
Página 25: 250 registros
Página 26: 250 registros
Página 27: 250 registros
Página 28: 250 registros
Página 29: 250 registros
Página 30: 250 registros
Página 31: 250 registros
Página 32: 250 registros
Página 33: 250 registros
Página 34: 250 registros
Página 35: 250 registros
Página 36: 250 registros
Página 37: 250 registros
Página 38: 250 registros
Página 39: 250 registros
Página 40: 250 registros
Página 41: 250 registros
Página 42: 250 registros
Página 43: 250 registros
Página 44: 250 registros
Página 45: 250 registros
Página 46: 250 registros
Página 47: 250 registros
Página 48: 250 registros
Página 49: 250 registros
Página 50: 250 registros
Página 51: 250 registros
Página 52: 250 registros
Página 53: 250 registros
Página 54: 250 registros
Página 55: 250 registros
Página 56: 250 registros
Página 57: 250 registros
Página 58: 158 registros

In [8]:
leads.columns

Index(['Tabulação Realizada', 'Nome Completo', 'Nome', 'Sobrenome', 'Email',
       'Celular', 'Telefone', 'ID Lead', 'Data Criação', 'Unidade Form',
       'Situação Funil', 'Origem Lead', 'Canal', 'Inscrição Atual', 'cpf',
       'Idade', 'Concurso Atual', 'Concurso de Origem', 'Data Nascimento',
       'Oferta Atual', 'Unidade Lead', 'Linha de Negócio', 'Proprietário',
       'Última Tabulação', 'Nacionalidade', 'Estado Civil', 'Sexo',
       'Órgão Expedidor', 'RG', 'Cor/Raça', 'Tabulação Lead',
       'Detalhamento Tabulação'],
      dtype='str')

In [9]:
colunas = ['ID Lead','Nome Completo','Inscrição Atual', 'Concurso Atual']

leads = leads[colunas]

In [20]:
# juntando as duas informações


df = pd.merge(leads, avaliacoes_agrupado, how='left', left_on='Inscrição Atual', right_on='cad_inscricaocandidatoid')

In [21]:
df.head(5)

,ID Lead,Nome Completo,Inscrição Atual,Concurso Atual,cad_inscricaocandidatoid,cad_valor
0,{A6EF1922-55B8-F111-AAAE-000D3AC0F764},Maria Gabriela Rodrigues Siqueira,NaN,NaN,NaN,NaN
1,{42E59D8D-54B8-F111-AAAD-00224836DCCC},Karolaine Teste,CAN-007220-TRI,Transferencia - Faculdade Serra Dourada Lorena,CAN-007220-TRI,0.0
2,{1A2EE67B-54B8-F111-AAAD-7CED8DB11FB7},Helena Beatriz Lago de Souza,CAN-007219-TRI,Vestibular Online - Faculdade Serra Dourada Al...,CAN-007219-TRI,0.0
3,{910401FA-270F-4ECC-8770-997431B8D267},Kymberly Dandara Da Silva Tenorio,NaN,Segunda Graduação- Faculdade Serra Dourada Alt...,NaN,NaN
4,{12F9819A-50B8-F111-AAAE-6045BD39BC63},Maria Eduarda de Sousa Faria,NaN,NaN,NaN,NaN

In [25]:
df[df['Concurso Atual'] == 'Vestibular de escolas Parceiras Lorena 27.1']

,ID Lead,Nome Completo,Inscrição Atual,Concurso Atual,cad_inscricaocandidatoid,cad_valor
34,{81E2F059-94B1-45A8-9E1C-E77C05ECE33C},Prova Tres Teste,CAN-007213-TRI,Vestibular de escolas Parceiras Lorena 27.1,CAN-007213-TRI,8.0
37,{4D788A87-D0A7-41BC-BB1C-7A4DB66A3CED},Prova Teste Dois,CAN-007212-TRI,Vestibular de escolas Parceiras Lorena 27.1,CAN-007212-TRI,6.0
48,{F0979084-0059-4DB2-B52D-4A598828C17F},Prova Um Teste,CAN-007209-TRI,Vestibular de escolas Parceiras Lorena 27.1,CAN-007209-TRI,0.0