In [24]:
# importando os scripts de consulta

import sys
import os

# Altera o caminho para a pasta raiz do projeto (um nível acima)
raiz_projeto = os.path.abspath(os.path.join(os.getcwd(), ".."))

# Adiciona a raiz do projeto ao caminho de busca do Python se ainda não estiver lá
if raiz_projeto not in sys.path:
    sys.path.append(raiz_projeto)

    
import pandas as pd
from scripts.crm_redacoes import load_redacoes
from corretor_redacoes import corrigir_redacao

In [25]:
redacoes_df = load_redacoes()

Página 1: 52 registros

In [26]:
redacoes_df.tail(1)

,cad_redacaoid,cad_name,cad_corrigidopor,cad_datacorrecao,cad_dataentrega,cad_datainicio,cad_datalimitetermino,cad_inscricao_redacao,cad_maximocaracteres,cad_minimocaracteres,cad_minimocaracterespreenchidos,cad_nota,cad_situacao,cad_temasredacao_redacao,cad_textoredacao,cad_totaldecaracteres
51,{36C9B3A1-7D66-F111-AB0C-7CED8DB11FB7},Redação Online - CAN-002101-TRI,TRIVENTO,2026-06-12T08:00:00-03:00,2026-06-12T13:42:00-03:00,2026-06-12T13:42:00-03:00,2026-06-12T15:12:00-03:00,NaN,3000,500,Sim,8,Corrigida,PERFIL EMPREENDEDOR,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...,514

In [27]:
redacoes_df['cad_situacao'].value_counts()

cad_situacao
Corrigida    49
Expirada      2
Entregue      1
Name: count, dtype: int64

In [28]:
redacoes_df = redacoes_df[redacoes_df['cad_situacao'] == "Entregue"]

In [29]:
redacoes_df

,cad_redacaoid,cad_name,cad_corrigidopor,cad_datacorrecao,cad_dataentrega,cad_datainicio,cad_datalimitetermino,cad_inscricao_redacao,cad_maximocaracteres,cad_minimocaracteres,cad_minimocaracterespreenchidos,cad_nota,cad_situacao,cad_temasredacao_redacao,cad_textoredacao,cad_totaldecaracteres
33,{1C54CC04-9CB7-F111-AAAE-6045BD39BC63},Redação Online - CAN-007175-TRI,NaN,NaN,2026-09-23T19:14:30-03:00,2026-09-23T19:13:39-03:00,2026-09-23T20:43:39-03:00,CAN-007175-TRI,3000,500,Sim,NaN,Entregue,DESIGUALDADES REGIONAIS,kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...,520

In [30]:
redacoes_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 33 to 33
Data columns (total 16 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   cad_redacaoid                    1 non-null      str
 1   cad_name                         1 non-null      str
 2   cad_corrigidopor                 0 non-null      str
 3   cad_datacorrecao                 0 non-null      str
 4   cad_dataentrega                  1 non-null      str
 5   cad_datainicio                   1 non-null      str
 6   cad_datalimitetermino            1 non-null      str
 7   cad_inscricao_redacao            1 non-null      str
 8   cad_maximocaracteres             1 non-null      str
 9   cad_minimocaracteres             1 non-null      str
 10  cad_minimocaracterespreenchidos  1 non-null      str
 11  cad_nota                         0 non-null      str
 12  cad_situacao                     1 non-null      str
 13  cad_temasredacao_redacao         1 non-null      str
 14  cad_textoredacao                 1 non-null      str
 15  cad_totaldecaracteres            1 non-null      str
dtypes: str(16)
memory usage: 1002.0 bytes

In [31]:
# tratamentos nos tipos das colunas
colunas = redacoes_df.columns

# formato das datas 2026-09-23T19:14:30-03:00
for coluna in colunas:
    if 'data' in coluna:
        redacoes_df[coluna] = pd.to_datetime(
            redacoes_df[coluna],
            format="%Y-%m-%dT%H:%M:%S%z",
            errors="coerce",
        )

# tratamento da coluna id
redacoes_df['cad_redacaoid'] = redacoes_df['cad_redacaoid'].astype(str).str.replace('{', '').str.replace('}', '')

redacoes_df['cad_nota'] = redacoes_df['cad_nota'].astype(float)

In [32]:
redacoes_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 33 to 33
Data columns (total 16 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   cad_redacaoid                    1 non-null      str
 1   cad_name                         1 non-null      str
 2   cad_corrigidopor                 0 non-null      str
 3   cad_datacorrecao                 0 non-null      datetime64[s]
 4   cad_dataentrega                  1 non-null      datetime64[us, UTC-03:00]
 5   cad_datainicio                   1 non-null      datetime64[us, UTC-03:00]
 6   cad_datalimitetermino            1 non-null      datetime64[us, UTC-03:00]
 7   cad_inscricao_redacao            1 non-null      str
 8   cad_maximocaracteres             1 non-null      str
 9   cad_minimocaracteres             1 non-null      str
 10  cad_minimocaracterespreenchidos  1 non-null      str
 11  cad_nota                         0 non-null      float64
 12  cad_situacao                     1 non-null      str
 13  cad_temasredacao_redacao         1 non-null      str
 14  cad_textoredacao                 1 non-null      str
 15  cad_totaldecaracteres            1 non-null      str
dtypes: datetime64[s](1), datetime64[us, UTC-03:00](3), float64(1), str(11)
memory usage: 920.0 bytes

In [33]:
for idx, linha in redacoes_df.iterrows():
    texto_redacao = linha['cad_textoredacao']
    nota_ia = corrigir_redacao(texto_redacao)
    print(f"Redação ID: {linha['cad_redacaoid']}, Nota IA: {nota_ia}")

    redacoes_df.at[idx, 'cad_nota'] = nota_ia

Redação ID: 1C54CC04-9CB7-F111-AAAE-6045BD39BC63, Nota IA: 1

In [34]:
redacoes_df

,cad_redacaoid,cad_name,cad_corrigidopor,cad_datacorrecao,cad_dataentrega,cad_datainicio,cad_datalimitetermino,cad_inscricao_redacao,cad_maximocaracteres,cad_minimocaracteres,cad_minimocaracterespreenchidos,cad_nota,cad_situacao,cad_temasredacao_redacao,cad_textoredacao,cad_totaldecaracteres
33,1C54CC04-9CB7-F111-AAAE-6045BD39BC63,Redação Online - CAN-007175-TRI,NaN,NaT,2026-09-23 19:14:30-03:00,2026-09-23 19:13:39-03:00,2026-09-23 20:43:39-03:00,CAN-007175-TRI,3000,500,Sim,1.0,Entregue,DESIGUALDADES REGIONAIS,kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...,520

In [35]:
redacoes_df['cad_corrigidopor'] = 'IA Trivento'

In [36]:
# renomeação das colunas
mapeamento_colunas = {
'cad_redacaoid': 'Id',
'cad_name': 'Assunto',
'cad_corrigidopor': 'Corrigido Por',
'cad_datacorrecao': 'Data da Correção',
'cad_dataentrega': 'Data de Entrega',
'cad_datainicio': 'Data de Início',
'cad_datalimitetermino': 'Data Limite para o Término',
'cad_inscricao_redacao': 'Inscrição',
'cad_maximocaracteres': 'Máximo de Caracteres',
'cad_minimocaracteres': 'Mínimo de Caracteres',
'cad_minimocaracterespreenchidos': 'Mínimo de Caracteres Preenchidos',
'cad_nota': 'Nota',
'cad_situacao': 'Situação',
'cad_temasredacao_redacao': 'Tema da Redação',
'cad_textoredacao': 'Texto da Redação',
'cad_totaldecaracteres': 'Total de Caracteres'
}

redacoes_df.rename(columns=mapeamento_colunas, inplace=True)

In [37]:
redacoes_df

,Id,Assunto,Corrigido Por,Data da Correção,Data de Entrega,Data de Início,Data Limite para o Término,Inscrição,Máximo de Caracteres,Mínimo de Caracteres,Mínimo de Caracteres Preenchidos,Nota,Situação,Tema da Redação,Texto da Redação,Total de Caracteres
33,1C54CC04-9CB7-F111-AAAE-6045BD39BC63,Redação Online - CAN-007175-TRI,IA Trivento,NaT,2026-09-23 19:14:30-03:00,2026-09-23 19:13:39-03:00,2026-09-23 20:43:39-03:00,CAN-007175-TRI,3000,500,Sim,1.0,Entregue,DESIGUALDADES REGIONAIS,kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...,520